server:
  port: 8761

eureka:
  client:
    registerWithEureka: false  # used to not register eureka service with itself
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0
  instance:
    hostname: localhost
